run:
  tests: false

issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    # - dupl
    - exhaustive
    # - exhaustivestruct
    - goconst
    - godot
    - godox
    - gomnd
    - gomoddirectives
    - goprintffuncname
    - ifshort
    # - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - wrapcheck

  # disable default linters, they are already enabled in .golangci.yml
  disable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
