run:
  tests: false
  issues-exit-code: 0

issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - exhaustive
    - goconst
    - godot
    - godox
    - mnd
    - gomoddirectives
    - goprintffuncname
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - wrapcheck

  # disable default linters, they are already enabled in .golangci.yml
  disable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
