// Code generated by golex. DO NOT EDIT.

// Code generated by key/gen.go. DO NOT EDIT.

package tea

func detectSequence(buf []byte) (ok bool, width int, res Msg) {
	//
	// NB: The remainder of this code was carefully crafted to avoid
	// function calls, bounds checks and and escapes during the escape traversal.
	// When modifying this logic, be careful to inspect the generated
	// assembly (go build -gcflags='-v -S').
	//
	var c byte
	i := uint(0)
	var ktype KeyType
	var alt bool
	var runes []rune

yystate0:

	goto yystate1

	goto yystart1

yystate1:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
yystart1:
	switch {
	default:
		goto yyabort
	case c == ' ':
		goto yystate353
	case c == '\x1b':
		goto yystate3
	case c >= '\x01' && c <= '\x1a' || c >= '\x1c' && c <= '\x1f' || c == '\x7f':
		goto yystate2
	}

yystate2:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule229

yystate3:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ' ':
		goto yystate138
	case c == 'O':
		goto yystate139
	case c == '[':
		goto yystate148
	case c == '\x1b':
		goto yystate5
	case c >= '\x01' && c <= '\x1a' || c >= '\x1c' && c <= '\x1f' || c == '\x7f':
		goto yystate4
	}

yystate4:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule228

yystate5:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyrule228
	case c == 'O':
		goto yystate6
	case c == '[':
		goto yystate15
	}

yystate6:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate7
	case c == 'B':
		goto yystate8
	case c == 'C':
		goto yystate9
	case c == 'D':
		goto yystate10
	case c == 'P':
		goto yystate11
	case c == 'Q':
		goto yystate12
	case c == 'R':
		goto yystate13
	case c == 'S':
		goto yystate14
	}

yystate7:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule86

yystate8:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule87

yystate9:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule88

yystate10:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule89

yystate11:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule90

yystate12:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule91

yystate13:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule92

yystate14:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule93

yystate15:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '1':
		goto yystate16
	case c == '2':
		goto yystate72
	case c == '3':
		goto yystate90
	case c == '4':
		goto yystate100
	case c == '5':
		goto yystate102
	case c == '6':
		goto yystate104
	case c == '7':
		goto yystate106
	case c == '8':
		goto yystate111
	case c == 'A':
		goto yystate116
	case c == 'B':
		goto yystate117
	case c == 'C':
		goto yystate118
	case c == 'D':
		goto yystate119
	case c == 'F':
		goto yystate120
	case c == 'H':
		goto yystate121
	case c == 'O':
		goto yystate122
	case c == 'Z':
		goto yystate127
	case c == '[':
		goto yystate128
	case c == 'a':
		goto yystate134
	case c == 'b':
		goto yystate135
	case c == 'c':
		goto yystate136
	case c == 'd':
		goto yystate137
	}

yystate16:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '1':
		goto yystate17
	case c == '2':
		goto yystate19
	case c == '3':
		goto yystate21
	case c == '4':
		goto yystate23
	case c == '5':
		goto yystate25
	case c == '7':
		goto yystate30
	case c == '8':
		goto yystate35
	case c == '9':
		goto yystate40
	case c == ';':
		goto yystate45
	case c == '~':
		goto yystate71
	}

yystate17:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate18
	}

yystate18:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule27

yystate19:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate20
	}

yystate20:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule28

yystate21:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate22
	}

yystate22:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule29

yystate23:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate24
	}

yystate24:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule30

yystate25:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate26
	case c == '~':
		goto yystate29
	}

yystate26:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '2':
		goto yystate27
	}

yystate27:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate28
	}

yystate28:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule1

yystate29:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule31

yystate30:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate31
	case c == '~':
		goto yystate34
	}

yystate31:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '2':
		goto yystate32
	}

yystate32:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate33
	}

yystate33:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule2

yystate34:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule32

yystate35:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate36
	case c == '~':
		goto yystate39
	}

yystate36:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '2':
		goto yystate37
	}

yystate37:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate38
	}

yystate38:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule3

yystate39:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule33

yystate40:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate41
	case c == '~':
		goto yystate44
	}

yystate41:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '2':
		goto yystate42
	}

yystate42:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate43
	}

yystate43:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule4

yystate44:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule34

yystate45:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '2':
		goto yystate46
	case c == '5':
		goto yystate57
	case c == '6':
		goto yystate64
	}

yystate46:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate47
	case c == 'B':
		goto yystate48
	case c == 'C':
		goto yystate49
	case c == 'D':
		goto yystate50
	case c == 'F':
		goto yystate51
	case c == 'H':
		goto yystate52
	case c == 'P':
		goto yystate53
	case c == 'Q':
		goto yystate54
	case c == 'R':
		goto yystate55
	case c == 'S':
		goto yystate56
	}

yystate47:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule5

yystate48:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule6

yystate49:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule7

yystate50:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule8

yystate51:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule9

yystate52:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule10

yystate53:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule11

yystate54:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule12

yystate55:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule13

yystate56:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule14

yystate57:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate58
	case c == 'B':
		goto yystate59
	case c == 'C':
		goto yystate60
	case c == 'D':
		goto yystate61
	case c == 'F':
		goto yystate62
	case c == 'H':
		goto yystate63
	}

yystate58:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule15

yystate59:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule16

yystate60:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule17

yystate61:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule18

yystate62:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule19

yystate63:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule20

yystate64:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate65
	case c == 'B':
		goto yystate66
	case c == 'C':
		goto yystate67
	case c == 'D':
		goto yystate68
	case c == 'F':
		goto yystate69
	case c == 'H':
		goto yystate70
	}

yystate65:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule21

yystate66:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule22

yystate67:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule23

yystate68:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule24

yystate69:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule25

yystate70:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule26

yystate71:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule47

yystate72:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '0':
		goto yystate73
	case c == '1':
		goto yystate75
	case c == '3':
		goto yystate77
	case c == '4':
		goto yystate79
	case c == '5':
		goto yystate81
	case c == '6':
		goto yystate83
	case c == '8':
		goto yystate85
	case c == '9':
		goto yystate87
	case c == '~':
		goto yystate89
	}

yystate73:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate74
	}

yystate74:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule35

yystate75:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate76
	}

yystate76:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule36

yystate77:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate78
	}

yystate78:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule37

yystate79:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate80
	}

yystate80:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule38

yystate81:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate82
	}

yystate82:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule39

yystate83:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate84
	}

yystate84:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule40

yystate85:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate86
	}

yystate86:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule41

yystate87:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate88
	}

yystate88:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule42

yystate89:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule48

yystate90:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '1':
		goto yystate91
	case c == '2':
		goto yystate93
	case c == '3':
		goto yystate95
	case c == '4':
		goto yystate97
	case c == '~':
		goto yystate99
	}

yystate91:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate92
	}

yystate92:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule43

yystate93:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate94
	}

yystate94:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule44

yystate95:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate96
	}

yystate96:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule45

yystate97:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate98
	}

yystate98:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule46

yystate99:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule49

yystate100:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate101
	}

yystate101:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule50

yystate102:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate103
	}

yystate103:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule51

yystate104:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate105
	}

yystate105:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule52

yystate106:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '$':
		goto yystate107
	case c == '@':
		goto yystate108
	case c == '^':
		goto yystate109
	case c == '~':
		goto yystate110
	}

yystate107:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule53

yystate108:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule54

yystate109:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule55

yystate110:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule56

yystate111:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '$':
		goto yystate112
	case c == '@':
		goto yystate113
	case c == '^':
		goto yystate114
	case c == '~':
		goto yystate115
	}

yystate112:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule57

yystate113:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule58

yystate114:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule59

yystate115:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule60

yystate116:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule94

yystate117:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule95

yystate118:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule96

yystate119:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule97

yystate120:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule98

yystate121:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule99

yystate122:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate123
	case c == 'B':
		goto yystate124
	case c == 'C':
		goto yystate125
	case c == 'D':
		goto yystate126
	}

yystate123:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule61

yystate124:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule62

yystate125:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule63

yystate126:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule64

yystate127:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule100

yystate128:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate129
	case c == 'B':
		goto yystate130
	case c == 'C':
		goto yystate131
	case c == 'D':
		goto yystate132
	case c == 'E':
		goto yystate133
	}

yystate129:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule65

yystate130:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule66

yystate131:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule67

yystate132:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule68

yystate133:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule69

yystate134:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule101

yystate135:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule102

yystate136:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule103

yystate137:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule104

yystate138:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule227

yystate139:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == 'A':
		goto yystate140
	case c == 'B':
		goto yystate141
	case c == 'C':
		goto yystate142
	case c == 'D':
		goto yystate143
	case c == 'P':
		goto yystate144
	case c == 'Q':
		goto yystate145
	case c == 'R':
		goto yystate146
	case c == 'S':
		goto yystate147
	}

yystate140:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule206

yystate141:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule207

yystate142:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule208

yystate143:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule209

yystate144:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule210

yystate145:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule211

yystate146:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule212

yystate147:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule213

yystate148:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '0' || c >= '9' && c <= '?':
		goto yystate151
	case c == '1':
		goto yystate152
	case c == '2':
		goto yystate248
	case c == '3':
		goto yystate290
	case c == '4':
		goto yystate305
	case c == '5':
		goto yystate307
	case c == '6':
		goto yystate312
	case c == '7':
		goto yystate317
	case c == '8':
		goto yystate322
	case c == '@' || c == 'E' || c == 'G' || c >= 'I' && c <= 'N' || c >= 'P' && c <= 'Y' || c >= '\\' && c <= '`' || c >= 'e' && c <= '~':
		goto yystate150
	case c == 'A':
		goto yystate327
	case c == 'B':
		goto yystate328
	case c == 'C':
		goto yystate329
	case c == 'D':
		goto yystate330
	case c == 'F':
		goto yystate331
	case c == 'H':
		goto yystate332
	case c == 'O':
		goto yystate333
	case c == 'Z':
		goto yystate342
	case c == '[':
		goto yystate343
	case c == 'a':
		goto yystate349
	case c == 'b':
		goto yystate350
	case c == 'c':
		goto yystate351
	case c == 'd':
		goto yystate352
	case c >= ' ' && c <= '/':
		goto yystate149
	}

yystate149:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate150:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule225

yystate151:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate152:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '0' || c == '6' || c == ':' || c >= '<' && c <= '?':
		goto yystate151
	case c == '1':
		goto yystate153
	case c == '2':
		goto yystate155
	case c == '3':
		goto yystate157
	case c == '4':
		goto yystate159
	case c == '5':
		goto yystate161
	case c == '7':
		goto yystate168
	case c == '8':
		goto yystate175
	case c == '9':
		goto yystate182
	case c == ';':
		goto yystate189
	case c == '~':
		goto yystate247
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate153:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate154
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate154:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule159

yystate155:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate156
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate156:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule160

yystate157:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate158
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate158:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule161

yystate159:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate160
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate160:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule162

yystate161:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate162
	case c == '~':
		goto yystate167
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate162:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '0' || c == '1' || c >= '4' && c <= '?':
		goto yystate151
	case c == '2':
		goto yystate163
	case c == '3':
		goto yystate165
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate163:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate164
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate164:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule70

yystate165:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate166
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate166:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule71

yystate167:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule163

yystate168:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate169
	case c == '~':
		goto yystate174
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate169:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '0' || c == '1' || c >= '4' && c <= '?':
		goto yystate151
	case c == '2':
		goto yystate170
	case c == '3':
		goto yystate172
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate170:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate171
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate171:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule72

yystate172:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate173
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate173:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule73

yystate174:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule164

yystate175:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate176
	case c == '~':
		goto yystate181
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate176:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '0' || c == '1' || c >= '4' && c <= '?':
		goto yystate151
	case c == '2':
		goto yystate177
	case c == '3':
		goto yystate179
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate177:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate178
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate178:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule74

yystate179:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate180
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate180:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule75

yystate181:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule165

yystate182:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate183
	case c == '~':
		goto yystate188
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate183:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '0' || c == '1' || c >= '4' && c <= '?':
		goto yystate151
	case c == '2':
		goto yystate184
	case c == '3':
		goto yystate186
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate184:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate185
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate185:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule76

yystate186:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate187
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate187:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule77

yystate188:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule166

yystate189:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '0' || c == '1' || c >= '9' && c <= '?':
		goto yystate151
	case c == '2':
		goto yystate190
	case c == '3':
		goto yystate201
	case c == '4':
		goto yystate212
	case c == '5':
		goto yystate219
	case c == '6':
		goto yystate226
	case c == '7':
		goto yystate233
	case c == '8':
		goto yystate240
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate190:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '@' || c == 'E' || c == 'G' || c >= 'I' && c <= 'O' || c >= 'T' && c <= '~':
		goto yystate150
	case c == 'A':
		goto yystate191
	case c == 'B':
		goto yystate192
	case c == 'C':
		goto yystate193
	case c == 'D':
		goto yystate194
	case c == 'F':
		goto yystate195
	case c == 'H':
		goto yystate196
	case c == 'P':
		goto yystate197
	case c == 'Q':
		goto yystate198
	case c == 'R':
		goto yystate199
	case c == 'S':
		goto yystate200
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	}

yystate191:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule105

yystate192:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule106

yystate193:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule107

yystate194:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule108

yystate195:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule109

yystate196:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule110

yystate197:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule111

yystate198:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule112

yystate199:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule113

yystate200:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule114

yystate201:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '@' || c == 'E' || c == 'G' || c >= 'I' && c <= 'O' || c >= 'T' && c <= '~':
		goto yystate150
	case c == 'A':
		goto yystate202
	case c == 'B':
		goto yystate203
	case c == 'C':
		goto yystate204
	case c == 'D':
		goto yystate205
	case c == 'F':
		goto yystate206
	case c == 'H':
		goto yystate207
	case c == 'P':
		goto yystate208
	case c == 'Q':
		goto yystate209
	case c == 'R':
		goto yystate210
	case c == 'S':
		goto yystate211
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	}

yystate202:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule115

yystate203:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule116

yystate204:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule117

yystate205:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule118

yystate206:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule119

yystate207:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule120

yystate208:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule121

yystate209:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule122

yystate210:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule123

yystate211:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule124

yystate212:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '@' || c == 'E' || c == 'G' || c >= 'I' && c <= '~':
		goto yystate150
	case c == 'A':
		goto yystate213
	case c == 'B':
		goto yystate214
	case c == 'C':
		goto yystate215
	case c == 'D':
		goto yystate216
	case c == 'F':
		goto yystate217
	case c == 'H':
		goto yystate218
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	}

yystate213:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule125

yystate214:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule126

yystate215:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule127

yystate216:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule128

yystate217:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule129

yystate218:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule130

yystate219:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '@' || c == 'E' || c == 'G' || c >= 'I' && c <= '~':
		goto yystate150
	case c == 'A':
		goto yystate220
	case c == 'B':
		goto yystate221
	case c == 'C':
		goto yystate222
	case c == 'D':
		goto yystate223
	case c == 'F':
		goto yystate224
	case c == 'H':
		goto yystate225
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	}

yystate220:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule131

yystate221:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule132

yystate222:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule133

yystate223:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule134

yystate224:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule135

yystate225:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule136

yystate226:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '@' || c == 'E' || c == 'G' || c >= 'I' && c <= '~':
		goto yystate150
	case c == 'A':
		goto yystate227
	case c == 'B':
		goto yystate228
	case c == 'C':
		goto yystate229
	case c == 'D':
		goto yystate230
	case c == 'F':
		goto yystate231
	case c == 'H':
		goto yystate232
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	}

yystate227:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule137

yystate228:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule138

yystate229:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule139

yystate230:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule140

yystate231:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule141

yystate232:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule142

yystate233:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '@' || c == 'E' || c == 'G' || c >= 'I' && c <= '~':
		goto yystate150
	case c == 'A':
		goto yystate234
	case c == 'B':
		goto yystate235
	case c == 'C':
		goto yystate236
	case c == 'D':
		goto yystate237
	case c == 'F':
		goto yystate238
	case c == 'H':
		goto yystate239
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	}

yystate234:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule143

yystate235:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule144

yystate236:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule145

yystate237:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule146

yystate238:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule147

yystate239:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule148

yystate240:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '@' || c == 'E' || c == 'G' || c >= 'I' && c <= '~':
		goto yystate150
	case c == 'A':
		goto yystate241
	case c == 'B':
		goto yystate242
	case c == 'C':
		goto yystate243
	case c == 'D':
		goto yystate244
	case c == 'F':
		goto yystate245
	case c == 'H':
		goto yystate246
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	}

yystate241:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule149

yystate242:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule150

yystate243:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule151

yystate244:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule152

yystate245:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule153

yystate246:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule154

yystate247:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule179

yystate248:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '0':
		goto yystate249
	case c == '1':
		goto yystate254
	case c == '2' || c == '7' || c >= ':' && c <= '?':
		goto yystate151
	case c == '3':
		goto yystate259
	case c == '4':
		goto yystate264
	case c == '5':
		goto yystate269
	case c == '6':
		goto yystate274
	case c == '8':
		goto yystate279
	case c == '9':
		goto yystate284
	case c == '~':
		goto yystate289
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate249:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate250
	case c == '~':
		goto yystate253
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate250:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '3':
		goto yystate251
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '2' || c >= '4' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate251:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate252
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate252:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule78

yystate253:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule167

yystate254:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate255
	case c == '~':
		goto yystate258
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate255:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '3':
		goto yystate256
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '2' || c >= '4' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate256:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate257
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate257:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule79

yystate258:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule168

yystate259:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate260
	case c == '~':
		goto yystate263
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate260:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '3':
		goto yystate261
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '2' || c >= '4' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate261:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate262
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate262:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule80

yystate263:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule169

yystate264:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate265
	case c == '~':
		goto yystate268
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate265:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '3':
		goto yystate266
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '2' || c >= '4' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate266:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate267
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate267:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule81

yystate268:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule170

yystate269:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate270
	case c == '~':
		goto yystate273
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate270:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '3':
		goto yystate271
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '2' || c >= '4' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate271:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate272
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate272:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule82

yystate273:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule171

yystate274:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate275
	case c == '~':
		goto yystate278
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate275:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '3':
		goto yystate276
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '2' || c >= '4' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate276:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate277
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate277:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule83

yystate278:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule172

yystate279:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate280
	case c == '~':
		goto yystate283
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate280:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '3':
		goto yystate281
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '2' || c >= '4' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate281:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate282
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate282:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule84

yystate283:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule173

yystate284:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate285
	case c == '~':
		goto yystate288
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate285:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '3':
		goto yystate286
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '2' || c >= '4' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate286:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate287
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate287:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule85

yystate288:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule174

yystate289:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule180

yystate290:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '0' || c >= '5' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c == '1':
		goto yystate291
	case c == '2':
		goto yystate293
	case c == '3':
		goto yystate295
	case c == '4':
		goto yystate297
	case c == ';':
		goto yystate299
	case c == '~':
		goto yystate304
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate291:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate292
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate292:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule175

yystate293:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate294
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate294:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule176

yystate295:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate296
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate296:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule177

yystate297:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate298
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate298:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule178

yystate299:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '0' || c == '1' || c >= '4' && c <= '?':
		goto yystate151
	case c == '2':
		goto yystate300
	case c == '3':
		goto yystate302
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate300:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate301
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate301:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule155

yystate302:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate303
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate303:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule156

yystate304:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule181

yystate305:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate306
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate306:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule182

yystate307:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate308
	case c == '~':
		goto yystate311
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate308:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '3':
		goto yystate309
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '2' || c >= '4' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate309:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate310
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate310:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule157

yystate311:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule183

yystate312:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == ';':
		goto yystate313
	case c == '~':
		goto yystate316
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= ':' || c >= '<' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate313:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '3':
		goto yystate314
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '2' || c >= '4' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate314:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '~':
		goto yystate315
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= '@' && c <= '}':
		goto yystate150
	}

yystate315:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule158

yystate316:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule184

yystate317:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '$':
		goto yystate318
	case c == '@':
		goto yystate319
	case c == '^':
		goto yystate320
	case c == '~':
		goto yystate321
	case c >= ' ' && c <= '#' || c >= '%' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= 'A' && c <= ']' || c >= '_' && c <= '}':
		goto yystate150
	}

yystate318:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyrule185
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate319:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule186

yystate320:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule187

yystate321:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule188

yystate322:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyabort
	case c == '$':
		goto yystate323
	case c == '@':
		goto yystate324
	case c == '^':
		goto yystate325
	case c == '~':
		goto yystate326
	case c >= ' ' && c <= '#' || c >= '%' && c <= '/':
		goto yystate149
	case c >= '0' && c <= '?':
		goto yystate151
	case c >= 'A' && c <= ']' || c >= '_' && c <= '}':
		goto yystate150
	}

yystate323:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyrule189
	case c >= ' ' && c <= '/':
		goto yystate149
	case c >= '@' && c <= '~':
		goto yystate150
	}

yystate324:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule190

yystate325:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule191

yystate326:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule192

yystate327:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule214

yystate328:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule215

yystate329:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule216

yystate330:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule217

yystate331:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule218

yystate332:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule219

yystate333:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyrule225
	case c == 'A':
		goto yystate334
	case c == 'B':
		goto yystate335
	case c == 'C':
		goto yystate336
	case c == 'D':
		goto yystate337
	case c == 'a':
		goto yystate338
	case c == 'b':
		goto yystate339
	case c == 'c':
		goto yystate340
	case c == 'd':
		goto yystate341
	}

yystate334:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule193

yystate335:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule194

yystate336:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule195

yystate337:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule196

yystate338:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule197

yystate339:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule198

yystate340:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule199

yystate341:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule200

yystate342:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule220

yystate343:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	switch {
	default:
		goto yyrule225
	case c == 'A':
		goto yystate344
	case c == 'B':
		goto yystate345
	case c == 'C':
		goto yystate346
	case c == 'D':
		goto yystate347
	case c == 'E':
		goto yystate348
	}

yystate344:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule201

yystate345:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule202

yystate346:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule203

yystate347:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule204

yystate348:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule205

yystate349:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule221

yystate350:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule222

yystate351:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule223

yystate352:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule224

yystate353:
	if i >= uint(len(buf)) {
		c = 0
	} else {
		c = buf[i]
	}
	i++
	goto yyrule226

yyrule1: // \x1b\x1b\[15;2~
	{

		ktype = Key{Type: KeyF17}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule2: // \x1b\x1b\[17;2~
	{

		ktype = Key{Type: KeyF18}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule3: // \x1b\x1b\[18;2~
	{

		ktype = Key{Type: KeyF19}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule4: // \x1b\x1b\[19;2~
	{

		ktype = Key{Type: KeyF20}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule5: // \x1b\x1b\[1;2A
	{

		ktype = Key{Type: KeyShiftUp}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule6: // \x1b\x1b\[1;2B
	{

		ktype = Key{Type: KeyShiftDown}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule7: // \x1b\x1b\[1;2C
	{

		ktype = Key{Type: KeyShiftRight}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule8: // \x1b\x1b\[1;2D
	{

		ktype = Key{Type: KeyShiftLeft}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule9: // \x1b\x1b\[1;2F
	{

		ktype = Key{Type: KeyShiftEnd}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule10: // \x1b\x1b\[1;2H
	{

		ktype = Key{Type: KeyShiftHome}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule11: // \x1b\x1b\[1;2P
	{

		ktype = Key{Type: KeyF13}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule12: // \x1b\x1b\[1;2Q
	{

		ktype = Key{Type: KeyF14}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule13: // \x1b\x1b\[1;2R
	{

		ktype = Key{Type: KeyF15}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule14: // \x1b\x1b\[1;2S
	{

		ktype = Key{Type: KeyF16}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule15: // \x1b\x1b\[1;5A
	{

		ktype = Key{Type: KeyCtrlUp}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule16: // \x1b\x1b\[1;5B
	{

		ktype = Key{Type: KeyCtrlDown}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule17: // \x1b\x1b\[1;5C
	{

		ktype = Key{Type: KeyCtrlRight}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule18: // \x1b\x1b\[1;5D
	{

		ktype = Key{Type: KeyCtrlLeft}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule19: // \x1b\x1b\[1;5F
	{

		ktype = Key{Type: KeyCtrlEnd}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule20: // \x1b\x1b\[1;5H
	{

		ktype = Key{Type: KeyCtrlHome}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule21: // \x1b\x1b\[1;6A
	{

		ktype = Key{Type: KeyCtrlShiftUp}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule22: // \x1b\x1b\[1;6B
	{

		ktype = Key{Type: KeyCtrlShiftDown}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule23: // \x1b\x1b\[1;6C
	{

		ktype = Key{Type: KeyCtrlShiftRight}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule24: // \x1b\x1b\[1;6D
	{

		ktype = Key{Type: KeyCtrlShiftLeft}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule25: // \x1b\x1b\[1;6F
	{

		ktype = Key{Type: KeyCtrlShiftEnd}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule26: // \x1b\x1b\[1;6H
	{

		ktype = Key{Type: KeyCtrlShiftHome}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule27: // \x1b\x1b\[11~
	{

		ktype = Key{Type: KeyF1}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule28: // \x1b\x1b\[12~
	{

		ktype = Key{Type: KeyF2}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule29: // \x1b\x1b\[13~
	{

		ktype = Key{Type: KeyF3}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule30: // \x1b\x1b\[14~
	{

		ktype = Key{Type: KeyF4}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule31: // \x1b\x1b\[15~
	{

		ktype = Key{Type: KeyF5}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule32: // \x1b\x1b\[17~
	{

		ktype = Key{Type: KeyF6}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule33: // \x1b\x1b\[18~
	{

		ktype = Key{Type: KeyF7}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule34: // \x1b\x1b\[19~
	{

		ktype = Key{Type: KeyF8}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule35: // \x1b\x1b\[20~
	{

		ktype = Key{Type: KeyF9}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule36: // \x1b\x1b\[21~
	{

		ktype = Key{Type: KeyF10}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule37: // \x1b\x1b\[23~
	{

		ktype = Key{Type: KeyF11}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule38: // \x1b\x1b\[24~
	{

		ktype = Key{Type: KeyF12}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule39: // \x1b\x1b\[25~
	{

		ktype = Key{Type: KeyF13}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule40: // \x1b\x1b\[26~
	{

		ktype = Key{Type: KeyF14}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule41: // \x1b\x1b\[28~
	{

		ktype = Key{Type: KeyF15}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule42: // \x1b\x1b\[29~
	{

		ktype = Key{Type: KeyF16}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule43: // \x1b\x1b\[31~
	{

		ktype = Key{Type: KeyF17}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule44: // \x1b\x1b\[32~
	{

		ktype = Key{Type: KeyF18}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule45: // \x1b\x1b\[33~
	{

		ktype = Key{Type: KeyF19}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule46: // \x1b\x1b\[34~
	{

		ktype = Key{Type: KeyF20}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule47: // \x1b\x1b\[1~
	{

		ktype = Key{Type: KeyHome}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule48: // \x1b\x1b\[2~
	{

		ktype = Key{Type: KeyInsert}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule49: // \x1b\x1b\[3~
	{

		ktype = Key{Type: KeyDelete}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule50: // \x1b\x1b\[4~
	{

		ktype = Key{Type: KeyEnd}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule51: // \x1b\x1b\[5~
	{

		ktype = Key{Type: KeyPgUp}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule52: // \x1b\x1b\[6~
	{

		ktype = Key{Type: KeyPgDown}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule53: // \x1b\x1b\[7\$
	{

		ktype = Key{Type: KeyShiftHome}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule54: // \x1b\x1b\[7@
	{

		ktype = Key{Type: KeyCtrlShiftHome}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule55: // \x1b\x1b\[7\^
	{

		ktype = Key{Type: KeyCtrlHome}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule56: // \x1b\x1b\[7~
	{

		ktype = Key{Type: KeyHome}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule57: // \x1b\x1b\[8\$
	{

		ktype = Key{Type: KeyShiftEnd}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule58: // \x1b\x1b\[8@
	{

		ktype = Key{Type: KeyCtrlShiftEnd}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule59: // \x1b\x1b\[8\^
	{

		ktype = Key{Type: KeyCtrlEnd}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule60: // \x1b\x1b\[8~
	{

		ktype = Key{Type: KeyEnd}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule61: // \x1b\x1b\[OA
	{

		ktype = Key{Type: KeyShiftUp}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule62: // \x1b\x1b\[OB
	{

		ktype = Key{Type: KeyShiftDown}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule63: // \x1b\x1b\[OC
	{

		ktype = Key{Type: KeyShiftRight}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule64: // \x1b\x1b\[OD
	{

		ktype = Key{Type: KeyShiftLeft}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule65: // \x1b\x1b\[\[A
	{

		ktype = Key{Type: KeyF1}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule66: // \x1b\x1b\[\[B
	{

		ktype = Key{Type: KeyF2}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule67: // \x1b\x1b\[\[C
	{

		ktype = Key{Type: KeyF3}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule68: // \x1b\x1b\[\[D
	{

		ktype = Key{Type: KeyF4}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule69: // \x1b\x1b\[\[E
	{

		ktype = Key{Type: KeyF5}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule70: // \x1b\[15;2~
	{

		ktype = Key{Type: KeyF17}.Type
		goto key
		goto yystate0
	}
yyrule71: // \x1b\[15;3~
	{

		ktype = Key{Type: KeyF5, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule72: // \x1b\[17;2~
	{

		ktype = Key{Type: KeyF18}.Type
		goto key
		goto yystate0
	}
yyrule73: // \x1b\[17;3~
	{

		ktype = Key{Type: KeyF6, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule74: // \x1b\[18;2~
	{

		ktype = Key{Type: KeyF19}.Type
		goto key
		goto yystate0
	}
yyrule75: // \x1b\[18;3~
	{

		ktype = Key{Type: KeyF7, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule76: // \x1b\[19;2~
	{

		ktype = Key{Type: KeyF20}.Type
		goto key
		goto yystate0
	}
yyrule77: // \x1b\[19;3~
	{

		ktype = Key{Type: KeyF8, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule78: // \x1b\[20;3~
	{

		ktype = Key{Type: KeyF9, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule79: // \x1b\[21;3~
	{

		ktype = Key{Type: KeyF10, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule80: // \x1b\[23;3~
	{

		ktype = Key{Type: KeyF11, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule81: // \x1b\[24;3~
	{

		ktype = Key{Type: KeyF12, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule82: // \x1b\[25;3~
	{

		ktype = Key{Type: KeyF13, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule83: // \x1b\[26;3~
	{

		ktype = Key{Type: KeyF14, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule84: // \x1b\[28;3~
	{

		ktype = Key{Type: KeyF15, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule85: // \x1b\[29;3~
	{

		ktype = Key{Type: KeyF16, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule86: // \x1b\x1bOA
	{

		ktype = Key{Type: KeyUp, Alt: false}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule87: // \x1b\x1bOB
	{

		ktype = Key{Type: KeyDown, Alt: false}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule88: // \x1b\x1bOC
	{

		ktype = Key{Type: KeyRight, Alt: false}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule89: // \x1b\x1bOD
	{

		ktype = Key{Type: KeyLeft, Alt: false}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule90: // \x1b\x1bOP
	{

		ktype = Key{Type: KeyF1}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule91: // \x1b\x1bOQ
	{

		ktype = Key{Type: KeyF2}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule92: // \x1b\x1bOR
	{

		ktype = Key{Type: KeyF3}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule93: // \x1b\x1bOS
	{

		ktype = Key{Type: KeyF4}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule94: // \x1b\x1b\[A
	{

		ktype = Key{Type: KeyUp}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule95: // \x1b\x1b\[B
	{

		ktype = Key{Type: KeyDown}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule96: // \x1b\x1b\[C
	{

		ktype = Key{Type: KeyRight}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule97: // \x1b\x1b\[D
	{

		ktype = Key{Type: KeyLeft}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule98: // \x1b\x1b\[F
	{

		ktype = Key{Type: KeyEnd}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule99: // \x1b\x1b\[H
	{

		ktype = Key{Type: KeyHome}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule100: // \x1b\x1b\[Z
	{

		ktype = Key{Type: KeyShiftTab}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule101: // \x1b\x1b\[a
	{

		ktype = Key{Type: KeyShiftUp}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule102: // \x1b\x1b\[b
	{

		ktype = Key{Type: KeyShiftDown}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule103: // \x1b\x1b\[c
	{

		ktype = Key{Type: KeyShiftRight}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule104: // \x1b\x1b\[d
	{

		ktype = Key{Type: KeyShiftLeft}. /*Alt: true*/ Type
		alt = true
		goto key
		goto yystate0
	}
yyrule105: // \x1b\[1;2A
	{

		ktype = Key{Type: KeyShiftUp}.Type
		goto key
		goto yystate0
	}
yyrule106: // \x1b\[1;2B
	{

		ktype = Key{Type: KeyShiftDown}.Type
		goto key
		goto yystate0
	}
yyrule107: // \x1b\[1;2C
	{

		ktype = Key{Type: KeyShiftRight}.Type
		goto key
		goto yystate0
	}
yyrule108: // \x1b\[1;2D
	{

		ktype = Key{Type: KeyShiftLeft}.Type
		goto key
		goto yystate0
	}
yyrule109: // \x1b\[1;2F
	{

		ktype = Key{Type: KeyShiftEnd}.Type
		goto key
		goto yystate0
	}
yyrule110: // \x1b\[1;2H
	{

		ktype = Key{Type: KeyShiftHome}.Type
		goto key
		goto yystate0
	}
yyrule111: // \x1b\[1;2P
	{

		ktype = Key{Type: KeyF13}.Type
		goto key
		goto yystate0
	}
yyrule112: // \x1b\[1;2Q
	{

		ktype = Key{Type: KeyF14}.Type
		goto key
		goto yystate0
	}
yyrule113: // \x1b\[1;2R
	{

		ktype = Key{Type: KeyF15}.Type
		goto key
		goto yystate0
	}
yyrule114: // \x1b\[1;2S
	{

		ktype = Key{Type: KeyF16}.Type
		goto key
		goto yystate0
	}
yyrule115: // \x1b\[1;3A
	{

		ktype = Key{Type: KeyUp, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule116: // \x1b\[1;3B
	{

		ktype = Key{Type: KeyDown, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule117: // \x1b\[1;3C
	{

		ktype = Key{Type: KeyRight, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule118: // \x1b\[1;3D
	{

		ktype = Key{Type: KeyLeft, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule119: // \x1b\[1;3F
	{

		ktype = Key{Type: KeyEnd, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule120: // \x1b\[1;3H
	{

		ktype = Key{Type: KeyHome, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule121: // \x1b\[1;3P
	{

		ktype = Key{Type: KeyF1, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule122: // \x1b\[1;3Q
	{

		ktype = Key{Type: KeyF2, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule123: // \x1b\[1;3R
	{

		ktype = Key{Type: KeyF3, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule124: // \x1b\[1;3S
	{

		ktype = Key{Type: KeyF4, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule125: // \x1b\[1;4A
	{

		ktype = Key{Type: KeyShiftUp, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule126: // \x1b\[1;4B
	{

		ktype = Key{Type: KeyShiftDown, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule127: // \x1b\[1;4C
	{

		ktype = Key{Type: KeyShiftRight, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule128: // \x1b\[1;4D
	{

		ktype = Key{Type: KeyShiftLeft, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule129: // \x1b\[1;4F
	{

		ktype = Key{Type: KeyShiftEnd, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule130: // \x1b\[1;4H
	{

		ktype = Key{Type: KeyShiftHome, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule131: // \x1b\[1;5A
	{

		ktype = Key{Type: KeyCtrlUp}.Type
		goto key
		goto yystate0
	}
yyrule132: // \x1b\[1;5B
	{

		ktype = Key{Type: KeyCtrlDown}.Type
		goto key
		goto yystate0
	}
yyrule133: // \x1b\[1;5C
	{

		ktype = Key{Type: KeyCtrlRight}.Type
		goto key
		goto yystate0
	}
yyrule134: // \x1b\[1;5D
	{

		ktype = Key{Type: KeyCtrlLeft}.Type
		goto key
		goto yystate0
	}
yyrule135: // \x1b\[1;5F
	{

		ktype = Key{Type: KeyCtrlEnd}.Type
		goto key
		goto yystate0
	}
yyrule136: // \x1b\[1;5H
	{

		ktype = Key{Type: KeyCtrlHome}.Type
		goto key
		goto yystate0
	}
yyrule137: // \x1b\[1;6A
	{

		ktype = Key{Type: KeyCtrlShiftUp}.Type
		goto key
		goto yystate0
	}
yyrule138: // \x1b\[1;6B
	{

		ktype = Key{Type: KeyCtrlShiftDown}.Type
		goto key
		goto yystate0
	}
yyrule139: // \x1b\[1;6C
	{

		ktype = Key{Type: KeyCtrlShiftRight}.Type
		goto key
		goto yystate0
	}
yyrule140: // \x1b\[1;6D
	{

		ktype = Key{Type: KeyCtrlShiftLeft}.Type
		goto key
		goto yystate0
	}
yyrule141: // \x1b\[1;6F
	{

		ktype = Key{Type: KeyCtrlShiftEnd}.Type
		goto key
		goto yystate0
	}
yyrule142: // \x1b\[1;6H
	{

		ktype = Key{Type: KeyCtrlShiftHome}.Type
		goto key
		goto yystate0
	}
yyrule143: // \x1b\[1;7A
	{

		ktype = Key{Type: KeyCtrlUp, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule144: // \x1b\[1;7B
	{

		ktype = Key{Type: KeyCtrlDown, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule145: // \x1b\[1;7C
	{

		ktype = Key{Type: KeyCtrlRight, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule146: // \x1b\[1;7D
	{

		ktype = Key{Type: KeyCtrlLeft, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule147: // \x1b\[1;7F
	{

		ktype = Key{Type: KeyCtrlEnd, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule148: // \x1b\[1;7H
	{

		ktype = Key{Type: KeyCtrlHome, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule149: // \x1b\[1;8A
	{

		ktype = Key{Type: KeyCtrlShiftUp, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule150: // \x1b\[1;8B
	{

		ktype = Key{Type: KeyCtrlShiftDown, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule151: // \x1b\[1;8C
	{

		ktype = Key{Type: KeyCtrlShiftRight, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule152: // \x1b\[1;8D
	{

		ktype = Key{Type: KeyCtrlShiftLeft, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule153: // \x1b\[1;8F
	{

		ktype = Key{Type: KeyCtrlShiftEnd, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule154: // \x1b\[1;8H
	{

		ktype = Key{Type: KeyCtrlShiftHome, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule155: // \x1b\[3;2~
	{

		ktype = Key{Type: KeyInsert, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule156: // \x1b\[3;3~
	{

		ktype = Key{Type: KeyDelete, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule157: // \x1b\[5;3~
	{

		ktype = Key{Type: KeyPgUp, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule158: // \x1b\[6;3~
	{

		ktype = Key{Type: KeyPgDown, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule159: // \x1b\[11~
	{

		ktype = Key{Type: KeyF1}.Type
		goto key
		goto yystate0
	}
yyrule160: // \x1b\[12~
	{

		ktype = Key{Type: KeyF2}.Type
		goto key
		goto yystate0
	}
yyrule161: // \x1b\[13~
	{

		ktype = Key{Type: KeyF3}.Type
		goto key
		goto yystate0
	}
yyrule162: // \x1b\[14~
	{

		ktype = Key{Type: KeyF4}.Type
		goto key
		goto yystate0
	}
yyrule163: // \x1b\[15~
	{

		ktype = Key{Type: KeyF5}.Type
		goto key
		goto yystate0
	}
yyrule164: // \x1b\[17~
	{

		ktype = Key{Type: KeyF6}.Type
		goto key
		goto yystate0
	}
yyrule165: // \x1b\[18~
	{

		ktype = Key{Type: KeyF7}.Type
		goto key
		goto yystate0
	}
yyrule166: // \x1b\[19~
	{

		ktype = Key{Type: KeyF8}.Type
		goto key
		goto yystate0
	}
yyrule167: // \x1b\[20~
	{

		ktype = Key{Type: KeyF9}.Type
		goto key
		goto yystate0
	}
yyrule168: // \x1b\[21~
	{

		ktype = Key{Type: KeyF10}.Type
		goto key
		goto yystate0
	}
yyrule169: // \x1b\[23~
	{

		ktype = Key{Type: KeyF11}.Type
		goto key
		goto yystate0
	}
yyrule170: // \x1b\[24~
	{

		ktype = Key{Type: KeyF12}.Type
		goto key
		goto yystate0
	}
yyrule171: // \x1b\[25~
	{

		ktype = Key{Type: KeyF13}.Type
		goto key
		goto yystate0
	}
yyrule172: // \x1b\[26~
	{

		ktype = Key{Type: KeyF14}.Type
		goto key
		goto yystate0
	}
yyrule173: // \x1b\[28~
	{

		ktype = Key{Type: KeyF15}.Type
		goto key
		goto yystate0
	}
yyrule174: // \x1b\[29~
	{

		ktype = Key{Type: KeyF16}.Type
		goto key
		goto yystate0
	}
yyrule175: // \x1b\[31~
	{

		ktype = Key{Type: KeyF17}.Type
		goto key
		goto yystate0
	}
yyrule176: // \x1b\[32~
	{

		ktype = Key{Type: KeyF18}.Type
		goto key
		goto yystate0
	}
yyrule177: // \x1b\[33~
	{

		ktype = Key{Type: KeyF19}.Type
		goto key
		goto yystate0
	}
yyrule178: // \x1b\[34~
	{

		ktype = Key{Type: KeyF20}.Type
		goto key
		goto yystate0
	}
yyrule179: // \x1b\[1~
	{

		ktype = Key{Type: KeyHome}.Type
		goto key
		goto yystate0
	}
yyrule180: // \x1b\[2~
	{

		ktype = Key{Type: KeyInsert}.Type
		goto key
		goto yystate0
	}
yyrule181: // \x1b\[3~
	{

		ktype = Key{Type: KeyDelete}.Type
		goto key
		goto yystate0
	}
yyrule182: // \x1b\[4~
	{

		ktype = Key{Type: KeyEnd}.Type
		goto key
		goto yystate0
	}
yyrule183: // \x1b\[5~
	{

		ktype = Key{Type: KeyPgUp}.Type
		goto key
		goto yystate0
	}
yyrule184: // \x1b\[6~
	{

		ktype = Key{Type: KeyPgDown}.Type
		goto key
		goto yystate0
	}
yyrule185: // \x1b\[7\$
	{

		ktype = Key{Type: KeyShiftHome}.Type
		goto key
		goto yystate0
	}
yyrule186: // \x1b\[7@
	{

		ktype = Key{Type: KeyCtrlShiftHome}.Type
		goto key
		goto yystate0
	}
yyrule187: // \x1b\[7\^
	{

		ktype = Key{Type: KeyCtrlHome}.Type
		goto key
		goto yystate0
	}
yyrule188: // \x1b\[7~
	{

		ktype = Key{Type: KeyHome}.Type
		goto key
		goto yystate0
	}
yyrule189: // \x1b\[8\$
	{

		ktype = Key{Type: KeyShiftEnd}.Type
		goto key
		goto yystate0
	}
yyrule190: // \x1b\[8@
	{

		ktype = Key{Type: KeyCtrlShiftEnd}.Type
		goto key
		goto yystate0
	}
yyrule191: // \x1b\[8\^
	{

		ktype = Key{Type: KeyCtrlEnd}.Type
		goto key
		goto yystate0
	}
yyrule192: // \x1b\[8~
	{

		ktype = Key{Type: KeyEnd}.Type
		goto key
		goto yystate0
	}
yyrule193: // \x1b\[OA
	{

		ktype = Key{Type: KeyShiftUp}.Type
		goto key
		goto yystate0
	}
yyrule194: // \x1b\[OB
	{

		ktype = Key{Type: KeyShiftDown}.Type
		goto key
		goto yystate0
	}
yyrule195: // \x1b\[OC
	{

		ktype = Key{Type: KeyShiftRight}.Type
		goto key
		goto yystate0
	}
yyrule196: // \x1b\[OD
	{

		ktype = Key{Type: KeyShiftLeft}.Type
		goto key
		goto yystate0
	}
yyrule197: // \x1b\[Oa
	{

		ktype = Key{Type: KeyCtrlUp, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule198: // \x1b\[Ob
	{

		ktype = Key{Type: KeyCtrlDown, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule199: // \x1b\[Oc
	{

		ktype = Key{Type: KeyCtrlRight, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule200: // \x1b\[Od
	{

		ktype = Key{Type: KeyCtrlLeft, Alt: true}.Type
		alt = true
		goto key
		goto yystate0
	}
yyrule201: // \x1b\[\[A
	{

		ktype = Key{Type: KeyF1}.Type
		goto key
		goto yystate0
	}
yyrule202: // \x1b\[\[B
	{

		ktype = Key{Type: KeyF2}.Type
		goto key
		goto yystate0
	}
yyrule203: // \x1b\[\[C
	{

		ktype = Key{Type: KeyF3}.Type
		goto key
		goto yystate0
	}
yyrule204: // \x1b\[\[D
	{

		ktype = Key{Type: KeyF4}.Type
		goto key
		goto yystate0
	}
yyrule205: // \x1b\[\[E
	{

		ktype = Key{Type: KeyF5}.Type
		goto key
		goto yystate0
	}
yyrule206: // \x1bOA
	{

		ktype = Key{Type: KeyUp, Alt: false}.Type
		goto key
		goto yystate0
	}
yyrule207: // \x1bOB
	{

		ktype = Key{Type: KeyDown, Alt: false}.Type
		goto key
		goto yystate0
	}
yyrule208: // \x1bOC
	{

		ktype = Key{Type: KeyRight, Alt: false}.Type
		goto key
		goto yystate0
	}
yyrule209: // \x1bOD
	{

		ktype = Key{Type: KeyLeft, Alt: false}.Type
		goto key
		goto yystate0
	}
yyrule210: // \x1bOP
	{

		ktype = Key{Type: KeyF1}.Type
		goto key
		goto yystate0
	}
yyrule211: // \x1bOQ
	{

		ktype = Key{Type: KeyF2}.Type
		goto key
		goto yystate0
	}
yyrule212: // \x1bOR
	{

		ktype = Key{Type: KeyF3}.Type
		goto key
		goto yystate0
	}
yyrule213: // \x1bOS
	{

		ktype = Key{Type: KeyF4}.Type
		goto key
		goto yystate0
	}
yyrule214: // \x1b\[A
	{

		ktype = Key{Type: KeyUp}.Type
		goto key
		goto yystate0
	}
yyrule215: // \x1b\[B
	{

		ktype = Key{Type: KeyDown}.Type
		goto key
		goto yystate0
	}
yyrule216: // \x1b\[C
	{

		ktype = Key{Type: KeyRight}.Type
		goto key
		goto yystate0
	}
yyrule217: // \x1b\[D
	{

		ktype = Key{Type: KeyLeft}.Type
		goto key
		goto yystate0
	}
yyrule218: // \x1b\[F
	{

		ktype = Key{Type: KeyEnd}.Type
		goto key
		goto yystate0
	}
yyrule219: // \x1b\[H
	{

		ktype = Key{Type: KeyHome}.Type
		goto key
		goto yystate0
	}
yyrule220: // \x1b\[Z
	{

		ktype = Key{Type: KeyShiftTab}.Type
		goto key
		goto yystate0
	}
yyrule221: // \x1b\[a
	{

		ktype = Key{Type: KeyShiftUp}.Type
		goto key
		goto yystate0
	}
yyrule222: // \x1b\[b
	{

		ktype = Key{Type: KeyShiftDown}.Type
		goto key
		goto yystate0
	}
yyrule223: // \x1b\[c
	{

		ktype = Key{Type: KeyShiftRight}.Type
		goto key
		goto yystate0
	}
yyrule224: // \x1b\[d
	{

		ktype = Key{Type: KeyShiftLeft}.Type
		goto key
		goto yystate0
	}
yyrule225: // \x1b\[[\x30-\x3f]*[\x20-\x2f]*[\x40-\x7e]
	{

		return true, int(i - 1), unknownCSISequenceMsg(buf[:i-1])
	}
yyrule226: // \x20
	{

		ktype = KeySpace
		runes = spaceRunes
		goto key
		goto yystate0
	}
yyrule227: // \x1b\x20
	{

		ktype = KeySpace
		runes = spaceRunes
		alt = true
		goto key
		goto yystate0
	}
yyrule228: // \x1b([\x01-\x1f\x7f]|\n)
	{

		// alt + control char (including alt+escape, but not NUL
		// which will be handled by detectOneMsg()).
		alt = true
		ktype = KeyType(buf[1])
		goto key
		goto yystate0
	}
yyrule229: // [\x01-\x1a\x1c-\x1f\x7f]|\n
	if true { // avoid go vet determining the below panic will not be reached

		// solitary control char; but NOT single escape or NUL
		// which will be handled by detectOneMsg().
		ktype = KeyType(buf[0])
		goto key
		goto yystate0
	}
	panic("unreachable")

yyabort: // no lexem recognized
	// silence unused label errors for build and satisfy go vet reachability analysis
	{
		if false {
			goto yyabort
		}
		if false {
			goto yystate0
		}
		if false {
			goto yystate1
		}
	}

	return false, 0, nil

key:
	return true, int(i - 1), KeyMsg(Key{Type: ktype, Alt: alt, Runes: runes})
}
